version: '3'
services:
  auth-center-back:
    image: "fqrmix/user-auth-center-backend:latest"
    networks:
      - docker-private-network
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      TZ: "Europe/Moscow"
      JWT_SECRET: "${JWT_SECRET}"
      POSTGRES_URL: "${POSTGRES_URL}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    command: ["java", "-jar", "/app/spring-boot-application.jar"]

networks:
  docker-private-network:
    external: true
